dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"
cache:
  directories:
    - "$HOME/.ccache"
    - "$HOME/.local"
addons:
  apt:
    packages:
      - gperf
before_install:
  - export PATH="/usr/lib/ccache:$HOME/.local/bin:$PATH"
install:
  - pip install coverage codecov pyvcd bitarray Jinja2
  - git clone https://github.com/YosysHQ/yosys
  - (cd yosys && if ! yosys -V || [ $(git rev-parse HEAD $(yosys -V | awk 'match($0,/sha1 ([0-9a-f]+)/,m) { print m[1] }') | uniq | wc -l) != 1 ]; then make CONFIG=gcc ENABLE_ABC=0 PREFIX=$HOME/.local install; fi)
  - (git clone https://github.com/YosysHQ/SymbiYosys && cd SymbiYosys && make PREFIX=$HOME/.local install)
  - if ! yices -V; then (git clone https://github.com/SRI-CSL/yices2.git && cd yices2 && autoconf && ./configure --prefix=$HOME/.local && make && make install); fi
script:
  - python setup.py develop
  - coverage run -m unittest discover
  - codecov
matrix:
  fast_finish: true
  allow_failures:
  - python: "pypy3"
